### ISSUE TITLE
Typo in the networkservicemesh.io's Homepage!

### ISSUE THREAD

**Issue by n2vo** [networkservicemesh/site#200]
I noticed a typo in the first sentence describing NSM on networkservicemesh.io site.  It states “…(NSM) is he”, not “…(NSM) is the”.  

"Network Service Mesh (NSM) is **h**e Hybrid/Multi-cloud IP Service Mesh enabling:"

**Comment by caboteria** [comment]
The typo is indeed fixed on networkservicemesh.io.
