### ISSUE TITLE
Setup page points to old release

### ISSUE THREAD

**Issue by caboteria** [networkservicemesh/site#230]
The links on https://networkservicemesh.io/docs/setup/run/ use version 1.2.0 which at the moment is quite a few commits behind the current 1.5.0 release. Not sure if the samples should link to "main" or if they should be updated for each release but NSM is moving very quickly so it seems a shame to point new users to such an old version.

**Comment by acnodal-tc** [comment]
Fixed by https://github.com/networkservicemesh/site/pull/231

**Comment by denis-tingaikin** [comment]
@caboteria , @acnodal-tc Thanks guys!
