### ISSUE TITLE
Community page stopped showing red arrows when PR from one repo to another failed (or not finished)

### ISSUE THREAD

**Issue by d-uzlov** [networkservicemesh/site#252]
Community page:
- https://networkservicemesh.io/community

# Expected behavior

When there is an open pull request with an automatic update, community page should show a red arrow instead of black one.

# Current behavior

Relationships between repositories always use black arrows.

For example, this PR failed CI and is still not fixed by the time of writing this, but there is no indication of this in the community page:
- https://github.com/networkservicemesh/integration-k8s-kind/pull/837

**Comment by denis-tingaikin** [comment]
Fixed by https://github.com/networkservicemesh/site/pull/254
