### ISSUE TITLE
Describe how each component interacts with each other

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/site#262]
### Description
For new users, it is unclear how NSM components interact with each other, or how NSM works as a whole.
For example, how the data packets sent by nsc are passed to nse through forwarder, so that users can have a clear understanding of nsm macroscopically

**Comment by NikitaSkrynnik** [comment]
Describe next components:
- nsmgr
- forwarder (vpp, ovs)
- registry
- registry-proxy-dns
- nsmgr-proxy
- webhook
- cluster-info-k8s
- map-ip-k8s
- exclude-prefixes
- NSE
- NSC (external, API+sdk client)

**Comment by 316953425** [comment]
hi @glazychev-art @NikitaSkrynnik 
Where can I see the results of your document? Do you have a link? Thank you very much.

**Comment by NikitaSkrynnik** [comment]
@316953425 Hello. It's still in progress. We will tell you as soon as we create a PR with the description.

**Comment by 316953425** [comment]
> @316953425 Hello. It's still in progress. We will tell you as soon as we create a PR with the description.

hi @NikitaSkrynnik 
Great, looking forward to your notification, thank you very much

**Comment by denis-tingaikin** [comment]
Seems like done.
